from pathlib import Path

ROOT = Path(__file__).parent
LOGS = ROOT / "logs"
LOG_FILE = LOGS / "chronoseq.log"
DATA = ROOT / "data"
RAW = DATA / "raw"
METADATA_DIR = DATA / "metadata"
METADATA = METADATA_DIR / "metadata.csv"
FASTQ = DATA / "fastq"
REFERENCE = DATA / "reference"
INDEX = DATA / "index"
BOWTIE_INDEX = INDEX / "ecoli"
QC_RAW = DATA / "qc_raw"
MULTIQC_RAW = DATA / "multiqc_raw"
QC_TRIMMED = DATA / "qc_trimmed"
MULTIQC_TRIMMED = DATA / "multiqc_trimmed"
ALIGNMENTS = DATA / "alignments"
COUNTS = DATA / "counts"
RESULTS = DATA / "results"
TRIMMED = DATA / "trimmed"
RESOURCES = ROOT / "resources"
ADAPTERS = RESOURCES / "adapters" / "TruSeq3-PE.fa"
STRINGTIE = DATA / "stringtie"
SAMPLE_LIST = COUNTS / "sample_list.txt"
PREPDE = PREPDE = ROOT / "SOFTWARES" / "stringtie" / "prepDE.py3"
EDGER = (ROOT / "scripts" / "edger_analysis.R")
TRINITY_SAMPLES = COUNTS / "samples.txt"
TRINITY_RESULTS = RESULTS / "trinity"
TRINITY_MATRIX = COUNTS / "gene_count_matrix.tsv"
MAPPING_STATS = RESULTS / "mapping_stats"
PLOTS = RESULTS / "plots"
REPORT_TEMPLATE = ROOT / "templates" / "report_template.html"
REPORT = RESULTS / "report.html"
REFERENCE_DIR = DATA / "reference"